"""Sub-stage 7: Visual Review — photorealism / likeness / protected-mark check.

Replaces the Day-6 30-LOC auto-pass stub with the real Pro-vision check
that validates each Visualizer-generated image against three rules per
CONSTITUTION Law 6 + §8 Kill List + PROJECT_BRIEF §7 + §9:

  1. Photorealism — must read as 'editorial illustration', not a photo.
  2. Likeness — must NOT contain identifiable individual faces. Empty
     interiors, landscapes, equipment shots, silhouettes pass.
  3. Protected marks — must NOT contain Olympic rings, Paralympic Agitos,
     LA28 logomark, Olympic torch, Team USA logos, or any third-party
     corporate logo other than Google Cloud.

Implementation: one Pro-tier vision call per image (`gemini-3.1-pro-preview`).
Pro is the right tier — vision quality matters and Flash-Lite vision is
too brittle for Kill-List auto-DQ stakes. The prompt asks for all three
checks at once and returns a single JSON object per image.

Failure modes per BUILD_SPEC §17.1:
  - Vision call fails twice → emit Wire thinking ("hold — visual review
    stalled, defaulting to fail-closed"); return passed=False with
    reason='vision_call_unavailable'. The orchestrator regenerates,
    which is the right side to err on.
  - Photorealism fail → passed=False, reason='photorealistic'.
  - Likeness fail → passed=False, reason='identifiable_likeness'.
  - Protected mark → passed=False, reason='protected_mark_<name>'.

Cost ceiling axis = `gemini_pro` (BUILD_SPEC §15.3) — three Pro vision
calls per draft, tracked under publish_gate.

Voice text is procedural; no agent voice fragments are emitted from
this sub-stage (the orchestrator emits its own substage thinking).
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from agents.cost.counters import CostCeilingExceeded
from agents.publish_gate.types import VisualReviewResult
from agents.wire.emit import WireProxyNotReadyError

logger = logging.getLogger(__name__)


_DEFAULT_MODEL = "gemini-3.1-pro-preview"  # Pro vision tier (BUILD_SPEC §3.1).
_COST_AXIS = "gemini_pro"


# --- Vision prompt -----------------------------------------------------------

_PROMPT_TEMPLATE = """\
You are the Visual Review sub-stage of The Storyteller's Room Publish
Gate. You are inspecting an editorial-illustration image generated by
the Visualizer. The image must comply with three rules from the
project's CONSTITUTION Law 6 and §8 Kill List:

1. STYLIZED, NOT PHOTOREALISTIC — the image must read as an editorial
   illustration (painterly, graphic, broadcast-style). It must NOT
   look like a photograph or photo-realistic render of a real scene.

2. NO IDENTIFIABLE LIKENESS — the image must NOT contain any
   identifiable human face. Empty interiors, landscapes, facilities,
   equipment, distant silhouettes, and abstract figures are all fine.
   ANY recognizable face = fail.

3. NO PROTECTED MARKS — the image must NOT contain any of:
   Olympic rings (the five-ring logomark), Paralympic Agitos (the
   three-crescent logo), LA28 logomark, Olympic torch, Team USA logos,
   or any third-party corporate logo other than Google Cloud.

Inspect the image against all three rules and return a single JSON
object with this shape, no prose, no fences:

{{
  "is_photoreal": boolean,
  "has_likeness": boolean,
  "detected_marks": [string],
  "confidence_0_to_1": number
}}

`detected_marks` is an array of mark names that you detected (use
human-readable strings like "olympic_rings", "paralympic_agitos",
"olympic_torch", "team_usa_logo", "la28_logomark", or "third_party_logo:
<vendor>"). Empty array if no marks detected.

`confidence_0_to_1` is your overall confidence in this judgment. Be
rigorous: prefer false-positives (passed=False) to false-negatives
(passed=True) — the auto-DQ cost is asymmetric. If unsure, err toward
flagging."""


# --- Result helpers ----------------------------------------------------------


def _empty_check_result() -> dict:
    return {
        "is_photoreal": False,
        "has_likeness": False,
        "detected_marks": [],
        "confidence_0_to_1": 0.0,
    }


def _parse_check_json(text: str) -> dict | None:
    """Extract the first JSON object from `text`. Mirrors fact_check's parser."""
    if not text:
        return None
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        obj = json.loads(cleaned)
        if isinstance(obj, dict):
            return obj
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if not match:
        return None
    try:
        obj = json.loads(match.group(0))
        if isinstance(obj, dict):
            return obj
    except json.JSONDecodeError:
        return None
    return None


def _coerce_check_dict(raw: dict | None) -> dict:
    """Defensively coerce model JSON to the expected shape."""
    out = _empty_check_result()
    if not isinstance(raw, dict):
        return out
    out["is_photoreal"] = bool(raw.get("is_photoreal", False))
    out["has_likeness"] = bool(raw.get("has_likeness", False))
    marks = raw.get("detected_marks") or []
    if isinstance(marks, list):
        out["detected_marks"] = [
            str(m) for m in marks if isinstance(m, (str, int, float))
        ]
    try:
        out["confidence_0_to_1"] = float(raw.get("confidence_0_to_1", 0.0))
    except (TypeError, ValueError):
        out["confidence_0_to_1"] = 0.0
    return out


# --- The sub-stage -----------------------------------------------------------


class VisualReviewSubstage:
    """Sub-stage 7 — validates Visualizer assets against CONSTITUTION Law 6.

    The Day-7 real check. Public surface preserved from the Day-6 stub:
    `review(*, story_draft, visualizer_assets=..., wire=..., investigation_id=...)`
    returns a `VisualReviewResult` dict with `passed`, `regenerations`,
    `failed_reasons`, and `images_checked`.
    """

    def __init__(
        self,
        *,
        model_id: str = _DEFAULT_MODEL,
        cost_counter: Any | None = None,
    ) -> None:
        self._model_id = model_id
        self._cost_counter = cost_counter

    # -- Public surface -----------------------------------------------------

    async def review(
        self,
        *,
        story_draft: dict | None = None,  # kept for orchestrator-stub parity
        visualizer_assets: dict | None = None,
        wire: Any | None = None,
        investigation_id: str = "ambient",
        regenerations: int = 0,
    ) -> VisualReviewResult:
        """Run the Visual Review sub-stage.

        Args:
            story_draft: the StoryDraft (unused by the check itself; kept
                for parity with the Day-6 stub signature so the
                orchestrator calls into both shapes uniformly).
            visualizer_assets: dict from `Visualizer.generate_assets`,
                shape `{hero_url, hometown_panel_url, echo_panel_url}`.
                If None or empty, this sub-stage fails closed with
                `reason='no_assets'`.
            wire: optional Wire emitter for fail-closed thinking events.
            investigation_id: investigation context.
            regenerations: how many regenerations preceded this review
                pass. Persisted unchanged into the result for the audit.

        Returns:
            VisualReviewResult with passed / regenerations / failed_reasons /
            images_checked.
        """
        assets = visualizer_assets or {}
        urls = [
            ("hero", assets.get("hero_url")),
            ("hometown_panel", assets.get("hometown_panel_url")),
            ("historical_echo", assets.get("echo_panel_url")),
        ]
        urls = [(label, u) for label, u in urls if u]

        if not urls:
            # Fail closed — the orchestrator will regenerate.
            await self._safe_emit_thinking(
                wire,
                "*hold — visual review has no assets to inspect*",
                investigation_id=investigation_id,
            )
            return VisualReviewResult(
                regenerations=regenerations,
                passed=False,
                failed_reasons=["no_assets"],
                images_checked=[],
            )

        failed_reasons: list[str] = []
        images_checked: list[str] = []

        for label, url in urls:
            images_checked.append(url)
            try:
                check = await self.check_image(url)
            except _VisionCallFailed:
                # check_image already emitted a thinking event on the
                # second failure. Fail closed for THIS image.
                await self._safe_emit_thinking(
                    wire,
                    "*hold — visual review stalled, defaulting to "
                    "fail-closed (regenerate)*",
                    investigation_id=investigation_id,
                )
                failed_reasons.append("vision_call_unavailable")
                # Fail-closed at the FIRST vision-call failure — no
                # point asking the model to inspect the next image
                # if the vision endpoint is down.
                break

            if check.get("is_photoreal"):
                failed_reasons.append(f"photorealistic:{label}")
            if check.get("has_likeness"):
                failed_reasons.append(f"identifiable_likeness:{label}")
            for mark in check.get("detected_marks") or []:
                # Normalize to lowercase + underscore-safe. Each mark gets
                # its own reason so the audit doc can show what was hit.
                slug = re.sub(r"\W+", "_", str(mark).strip().lower()).strip("_")
                if slug:
                    failed_reasons.append(f"protected_mark_{slug}:{label}")

        passed = not failed_reasons

        return VisualReviewResult(
            regenerations=regenerations,
            passed=passed,
            failed_reasons=failed_reasons,
            images_checked=images_checked,
        )

    async def check_image(self, image_url: str) -> dict:
        """One Pro-vision call returning structured JSON about an image.

        Returns: `{is_photoreal, has_likeness, detected_marks,
                   confidence_0_to_1}`.

        Raises:
            CostCeilingExceeded: pre-check ceiling breach.
            _VisionCallFailed: both attempts at the Pro-vision call raised.
        """
        # Cost-counter pre-check. We check before each image so a single
        # over-budget call doesn't poison the rest of the pipeline.
        if self._cost_counter is not None:
            try:
                await self._cost_counter.assert_under_ceiling(
                    axis=_COST_AXIS, agent="publish_gate"
                )
            except CostCeilingExceeded:
                logger.info(
                    "visual_review: cost ceiling reached on image_url=%s",
                    image_url,
                )
                raise _VisionCallFailed(
                    "cost_ceiling exceeded on gemini_pro axis"
                ) from None

        last_exc: Exception | None = None
        for attempt in (1, 2):
            try:
                raw, in_tokens, out_tokens = await self._call_model_vision(
                    image_url
                )
                if self._cost_counter is not None:
                    try:
                        await self._cost_counter.increment(
                            agent="publish_gate",
                            sub_agent=None,
                            axis=_COST_AXIS,
                            model=self._model_id,
                            calls=1,
                            input_tokens=int(in_tokens or 0),
                            output_tokens=int(out_tokens or 0),
                        )
                    except Exception:
                        logger.exception(
                            "visual_review: cost_counter.increment failed"
                        )
                return _coerce_check_dict(raw)
            except Exception as e:
                last_exc = e
                logger.warning(
                    "visual_review.check_image: attempt %d/2 failed for %s: %s",
                    attempt, image_url, e,
                )

        # Both attempts failed.
        logger.error(
            "visual_review.check_image: vision call unavailable after retries: %s",
            last_exc,
        )
        raise _VisionCallFailed(
            f"vision call unavailable for {image_url}"
        ) from last_exc

    # -- Internals ---------------------------------------------------------

    async def _call_model_vision(
        self, image_url: str
    ) -> tuple[dict | None, int, int]:
        """One Pro-vision `generate_content` call returning (parsed_json, in, out).

        Uses the google-genai async client with a `Part.from_uri` for
        the GCS image. Vertex AI accepts `gs://` URIs directly in
        `fileData.fileUri` so we don't have to download bytes
        client-side. (If the URL is HTTPS, we still pass it through —
        google-genai will resolve it.)
        """
        try:
            from google import genai  # type: ignore[import-untyped]
            from google.genai import types as genai_types  # type: ignore[import-untyped]
        except ImportError as e:
            raise RuntimeError("google-genai not installed") from e

        client = genai.Client()
        # Build the multimodal contents list: image part + text prompt.
        # `Part.from_uri` works for `gs://` and `https://` URIs.
        mime = _guess_mime(image_url)
        image_part = genai_types.Part.from_uri(file_uri=image_url, mime_type=mime)
        text_part = genai_types.Part.from_text(text=_PROMPT_TEMPLATE)
        contents = [genai_types.Content(role="user", parts=[image_part, text_part])]
        config = genai_types.GenerateContentConfig(
            temperature=0.0,
            response_mime_type="application/json",
        )
        response = await client.aio.models.generate_content(
            model=self._model_id,
            contents=contents,
            config=config,
        )
        text = getattr(response, "text", "") or ""
        parsed = _parse_check_json(text)
        if parsed is None:
            raise RuntimeError(
                f"visual_review: vision returned non-JSON (head={text[:120]!r})"
            )
        usage = getattr(response, "usage_metadata", None)
        in_tokens = (
            int(getattr(usage, "prompt_token_count", 0) or 0)
            if usage is not None
            else 0
        )
        out_tokens = (
            int(getattr(usage, "candidates_token_count", 0) or 0)
            if usage is not None
            else 0
        )
        return parsed, in_tokens, out_tokens

    async def _safe_emit_thinking(
        self,
        wire: Any | None,
        message: str,
        *,
        investigation_id: str,
    ) -> None:
        if wire is None:
            return
        try:
            await wire.emit(
                {
                    "agent": "publish_gate",
                    "message": message,
                    "message_type": "thinking",
                    "mode": "live",
                },
                investigation_id=investigation_id,
            )
        except WireProxyNotReadyError:
            logger.warning(
                "visual_review: wire proxy not ready; cannot emit thinking event"
            )
        except Exception:
            logger.exception(
                "visual_review: failed to emit thinking event"
            )


# --- Internal sentinel exception ---------------------------------------------


class _VisionCallFailed(RuntimeError):
    """Raised internally when both vision-call attempts fail.

    Caught by `review()` and surfaced as `failed_reasons=['vision_call_unavailable']`.
    Not part of the public API — callers should look at `VisualReviewResult`.
    """


# --- Helpers -----------------------------------------------------------------


def _guess_mime(url: str) -> str:
    """Crude file-extension → mime mapping. Vertex AI accepts these directly."""
    if not isinstance(url, str):
        return "image/png"
    lower = url.lower()
    if lower.endswith(".jpg") or lower.endswith(".jpeg"):
        return "image/jpeg"
    if lower.endswith(".webp"):
        return "image/webp"
    return "image/png"


__all__ = ["VisualReviewSubstage"]
